version: "3.9"

services:

  envoy:
    container_name: app-envoy
    build:
      context: .
      dockerfile: ./docker/envoy/Dockerfile
    ports:
      - 8080:8080
      - 9000:9000
    volumes:
      - ./docker/envoy:/envoy
    entrypoint: ["/entry.sh", "envoy", "-c", "/envoy/envoy.yaml"]    


  postgres-users:
    container_name: postgres-users
    image: postgres:13.3
    env_file: ./docker/etc/db/.env
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
    command: -c "log_statement=all"

  access:
    container_name: access
    build: 
      context: .
      dockerfile: ./docker/access/Dockerfile
    ports:
      - 7070:7070
    depends_on:
      - postgres-users

volumes:
  access: {}