grpc:
  network: tcp
  bind: :7070

token:
  secret: "123213213211"
  algorithm: HS256

# postgresql database configuration.
db:
  driver: 'pgx'
  url: 'postgresql://postgres:qwerty@postgres-users:5432/access?sslmode=disable'
  max_limit: 1000

broker:
  url: "amqp://guest:guest@rabbitmq:5672/"

access:
  